version: "3.9"

services:
  esp32:
    build: .
    container_name: esp32_simulador
    environment:
      CODESPUNI: "123"
      ESP_NAME: "esp2"
      MQTT_BROKER: "192.168.200.24"
      MQTT_PORT: 1883
    networks:
      - mqttnet

networks:
  mqttnet:
    driver: bridge
